project:
  output-dir: _site
  type: website

website:
  title: "Kornia"
  description: ""
  page-navigation: true
  favicon: "tutorials/_static/img/kornia_logo_favicon.png"
  site-url: https://kornia.github.io/tutorials/
  repo-url: https://github.com/kornia/tutorials/
  repo-branch: master
  repo-actions: [edit, source, issue]
  google-analytics: ''
  open-graph: true

  twitter-card:
    site: "@sitehandle"

  search:
    location: navbar
    type: overlay

  navbar:
    collapse: false
    pinned: true
    search: true
    logo: "tutorials/_static/img/kornia_logo_mini.png"
    right:
      - icon: github
        href: https://github.com/kornia/
      - icon: twitter
        href: https://twitter.com/kornia_foss
      - icon: linkedin
        href: https://www.linkedin.com/company/kornia/

    left:
        - text: "Tutorials"
          file: index.qmd
        - text: "Docs"
          href: https://kornia.readthedocs.io
        - text: "About"
          href: https://kornia.readthedocs.io/en/latest/get-started/introduction.html
        - text: "Projects"
          menu:
            - text: Kornia
              href: "https://github.com/kornia/kornia"
            - text: Limbus
              href: "https://github.com/kornia/limbus"
            - text: Kornia-rs
              href: "https://github.com/kornia/kornia-rs"


  page-footer:
    center:
      - text: Copyright © 2023 Kornia. All Rights Reserved.
    right:
      - icon: question-circle-fill
        href: https://github.com/kornia/kornia/discussions
      - icon: lightbulb-fill
        href: https://github.com/kornia/kornia/
      - icon: twitter
        href: https://twitter.com/kornia_foss
      - icon: linkedin
        href: https://www.linkedin.com/company/kornia/

format:
  html:
    link-external-newwindow: false
    link-external-icon: false
    number-sections: false
    fig-responsive: true
    toc: true
    toc-depth: 5
    mainfont: "Open Sans, sans-serif"
    fontsize: 18px
    grid:
        body-width: 1350px
        margin-width: 380px
    theme:
      light:
        - sandstone
        - tutorials/_static/css/styles_light.scss
      dark:
        - sandstone
        - tutorials/_static/css/styles_dark.scss

    # Code
    code-copy: hover
    highlight-style: monokai
    code-link: true
    code-overflow: scroll
