name: Tutorials

on:
  workflow_dispatch:
  push:
    branches: [master, test-me-*]
  pull_request:
  schedule:
    - cron: "0 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tutorials - ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.pytorch-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: false
      matrix:
        os: ['Ubuntu']
        python-version: ['3.8', '3.10']
        pytorch-version: ['2.0.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup environment
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pytorch
      shell: bash
      run: pip install torch==${{ matrix.pytorch-version }} torchvision --index-url https://download.pytorch.org/whl/cpu


    - name: Install dependencies
      shell: bash -l {0}
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install -U kornia_moons==0.2.8

    - name: Check deps
      shell: bash -l {0}
      run: make check-deps

    - name: Generate tutorials
      shell: bash -l {0}
      run: make generate

    - name: Run tutorials
      shell: bash -l {0}
      run: make execute

  build:
    needs: test
    name: Build tutorials - ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.pytorch-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: ['Ubuntu']
        python-version: ['3.10']
        pytorch-version: ['2.0.1']

    steps:
    - uses: actions/checkout@v3

    - name: Setup conda dependencies
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version:  ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install pytorch=${{ matrix.pytorch-version }} torchvision cpuonly -c pytorch
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - uses: quarto-dev/quarto-actions/setup@v2

    - name: Check deps
      shell: bash -l {0}
      run: make check-deps

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html
        path: .
