name: Generate docs and deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [master, test-me-*, migration/quarto]

jobs:
  deploy:
    name: Deploy tutorials - ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.pytorch-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      fail-fast: true
      matrix:
        os: ['Ubuntu']
        python-version: ['3.10']
        pytorch-version: ['2.0.0']

    steps:
      - uses: actions/checkout@v3
      - name: Setup conda dependencies
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version:  ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda install pytorch=${{ matrix.pytorch-version }} torchvision cpuonly -c pytorch
          make setup
      - name: Build the pages
        shell: bash -l {0}
        run: make build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
          publish_dir: ./_site
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
