name: Generate docs and deploy to GitHub Pages
on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  deploy:
    name: Deploy tutorials - ${{ matrix.os }}, ${{ matrix.python-version }}, ${{ matrix.pytorch-version }}
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: ['ubuntu']
        kornia-ref: ['main']

    steps:
    - uses: kornia/workflows/.github/actions/env@v1.4.1
      with:
        ref: ${{ matrix.kornia-ref }}

    - uses: actions/checkout@v4
      with:
        repository: 'kornia/tutorials'
        path: 'tutorials-repo/'

    - name: Install dependencies
      working-directory: ./tutorials-repo/
      shell: bash -l {0}
      run: make setup

    - uses: quarto-dev/quarto-actions/setup@v2

    - name: Render Quarto Project
      uses: quarto-dev/quarto-actions/render@v2
      with:
        to: html
        path: ./tutorials-repo/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        publish_dir: ./tutorials-repo/_site
        user_name: github-actions[bot]
        user_email: 41898282+github-actions[bot]@users.noreply.github.com
